;; Copyright (c) 2024-2026 Grumatic, Inc.
;; SPDX-License-Identifier: MIT
;; Licensed under the MIT License. See LICENSE at the repository root.

(ns ai.brainyard.agent.core.agent
  "Core Agent defrecord — the stateful agent entity.

   Agent is a defrecord implementing:
   - IAgent            — identity, processing, tools, state
   - IAgentLifecycle   — start/stop/running
   - IAgentState       — deep state access, BT accessors
   - IAgentBTIntegration — methods expected by BT extended nodes in bt.clj
   - IAgentMemoryAccess — memory manager access, recall/remember
   - java.io.Closeable — cleanup on close

   The agent holds:
   - !state atom with:
     {:config          {...}    ;; agent configuration
      :st-memory-init  <atom of initial st-memory map>
      :behavior-tree   {:tree ... :context {:st-memory <atom> ...}}
      :memory-manager  <MemoryManager>
      :session-store   <ISessionStore>
      :runtime         {:future ... :cancelled? ... :action-permissions ...}
      :clj-agent       <clojure.lang.Agent>  ;; for serialized async execution
      :status          :created} ;; :created, :idle, :running, :paused, :cancelled, :stopped
   - !session atom (shared across agents in the same agent-session;
     carries :user-id and :session-id — the Agent record does NOT hold these):
     {:session-id ... :user-id ... :config {...} :messages [...] :data {...}}"
  (:require [clojure.string]
            [ai.brainyard.mulog.interface :as mulog]
            [ai.brainyard.agent.core.protocol :as proto]
            [ai.brainyard.agent.core.session :as session]
            [ai.brainyard.agent.core.runtime :as runtime]
            [ai.brainyard.agent.core.memory :as agent-mem]
            [ai.brainyard.agent.core.bt :as agent-bt]
            [ai.brainyard.agent.core.context :as context]
            [ai.brainyard.agent.core.tool :as tool]
            [ai.brainyard.agent.core.config :as config]
            [ai.brainyard.agent.core.hooks :as hooks]
            [ai.brainyard.clj-llm.interface :as llm]
            [ai.brainyard.memory.interface :as mem]
            [ai.brainyard.util.interface :as util]))

;; ============================================================================
;; Agent Registry (flat, keyed by globally-unique agent-id)
;;
;; Agent-id keys follow the convention :<defagent-type>/<suffix>, e.g.
;; :coact-agent/crimson-parrot-42. Uniqueness is enforced by the suffix
;; (generated by `generate-instance-id`). The defagent-type is recoverable
;; from any instance-id via (namespace agent-id) or proto/defagent-type.
;;
;; `!session` carries user-id / session-id — the registry does not.
;; ============================================================================

(defonce ^:private !agent-registry (atom {}))
(defonce ^:private !agent-creation-locks (atom {}))

(defn- get-or-create-lock
  "Get or create a per-key lock object for agent creation serialization."
  [key]
  (let [lock (Object.)]
    (-> (swap! !agent-creation-locks
               (fn [m] (if (contains? m key) m (assoc m key lock))))
        (get key))))

(defn generate-instance-id
  "Generate a unique agent instance-id in :<defagent-type>/<suffix> format.
   defagent-type must be a keyword naming a registered defagent."
  [defagent-type]
  {:pre [(keyword? defagent-type)]}
  (keyword (name defagent-type) (util/gen-random-words)))

(defn register-agent
  "Register an agent under its agent-id."
  [agent]
  (let [aid (proto/agent-id agent)]
    (swap! !agent-registry assoc aid agent)
    (mulog/info ::agent-registered :agent-id aid)
    agent))

(defn unregister-agent
  "Unregister an agent by agent-id."
  [agent-id]
  (swap! !agent-registry dissoc agent-id)
  (mulog/info ::agent-unregistered :agent-id agent-id))

(defn get-agent
  "Get an agent by its globally-unique agent-id."
  [agent-id]
  (get @!agent-registry agent-id))

(defn list-agents
  "List all registered agents."
  []
  (vals @!agent-registry))

(defn list-agents-for-session
  "List all agents belonging to a given agent-session-id."
  [session-id]
  (->> (vals @!agent-registry)
       (filter #(= session-id (proto/session-id %)))
       vec))

(defn reset-agent-registry!
  "Reset the agent registry and creation locks. For testing — clears all registered agents."
  []
  (reset! !agent-registry {})
  (reset! !agent-creation-locks {}))

;; ============================================================================
;; Sub-Agent Activity Forwarding
;; ============================================================================

(defn- attach-activity-forward-watch!
  "Attach a watch on a sub-agent's st-memory that forwards display-stage
   changes to the shared !session :agent-activity vector.
   Only attaches when the agent has a parent (i.e., is a sub-agent)."
  [agent]
  (let [!state  (:!state agent)
        !sess   (:!session agent)
        st-atom (get-in @!state [:behavior-tree :context :st-memory])
        ag-id   (keyword (:agent-id agent))
        ag-name (or (get-in @!state [:meta :name]) (:agent-id agent))]
    (when (and st-atom !sess (runtime/get-parent-agent !state))
      (add-watch st-atom ::forward-activity
                 (fn [_ _ old new]
                   (let [stage (:display-stage new)]
                     (when (and (some? stage)
                                (not= (:display-stage old) stage))
                       (let [data (case stage
                                   ;; Tool-results: forward only the delta
                                    :tool-results
                                    (let [old-r (or (:tool-results old) [])
                                          new-r (or (:tool-results new) [])]
                                      {:tool-results (if (> (count new-r) (count old-r))
                                                       (subvec new-r (count old-r))
                                                       new-r)})
                                   ;; All other stages: snapshot relevant keys
                                    (select-keys new
                                                 [:iteration-count :last-reasoning
                                                  :tool-calls :tool-results
                                                  :observation :goal-achieved :goal-reasoning
                                                  :eval-display :todo-list :answer
                                                  :terminated :iterations-exhausted
                                                  :question]))]
                         (swap! !sess session/append-agent-activity
                                {:agent-id   ag-id
                                 :agent-name (if (keyword? ag-name) (name ag-name) (str ag-name))
                                 :stage      stage
                                 :data       data
                                 :timestamp  (System/currentTimeMillis)})))))))))

(defn- detach-activity-forward-watch!
  "Remove the forwarding watch from a sub-agent's st-memory."
  [agent]
  (when-let [st-atom (get-in @(:!state agent) [:behavior-tree :context :st-memory])]
    (remove-watch st-atom ::forward-activity)))

(defn- fire-agent-done-activity!
  "Send an :agent-done activity event to the shared session.
   Called when a sub-agent's ask completes (success or failure)."
  [agent]
  (let [!state  (:!state agent)
        !sess   (:!session agent)
        ag-id   (keyword (:agent-id agent))
        ag-name (or (get-in @!state [:meta :name]) (:agent-id agent))]
    (when (and !sess (runtime/get-parent-agent !state))
      (swap! !sess session/append-agent-activity
             {:agent-id   ag-id
              :agent-name (if (keyword? ag-name) (name ag-name) (str ag-name))
              :stage      :agent-done
              :data       {}
              :timestamp  (System/currentTimeMillis)}))))

;; ============================================================================
;; Lifecycle Hook Helper
;; ============================================================================

;; Agent lifecycle events are fired through ai.brainyard.agent.core.hooks.
;; Event catalog — see hooks/event-catalog for the authoritative list:
;;   :agent.session/created    {:session-id :user-id :session}   ;; fired in core.session
;;   :agent.session/resumed    {:session-id :user-id :session}   ;; fired in core.session
;;   :agent.session/closed     {:session-id :user-id :session}   ;; fired in core.session/delete-session
;;   :agent.instance/created   {:agent agent}
;;   :agent.instance/closed    {:agent agent}
;;   :agent.ask/pre            {:agent agent :input input}
;;   :agent.ask/post           {:agent agent :input input :result result}

;; ============================================================================
;; Agent Record
;; ============================================================================

(defn- inject-resume-note!
  "When the agent was resumed from a pause with a user note, fold the note into
   the *running* loop so the next iteration's prompt carries it with directive
   force. We append to st-memory `:question` — the ACTIVE TASK that both the
   react and coact loops render as the primary objective each iteration — so
   the note actually steers the remaining work. (Appending to `:conversation`
   alone lands it in the auxiliary `## Conversation History` section, which the
   LLM treats as background and deprioritizes against the original question — a
   live test showed the agent ignoring it there.) A `:conversation` breadcrumb
   and a session trace are kept for visibility. No-op when there is no pending
   note or no `:question`. Called from `apply-resume-note!` at every BT
   checkpoint, so it fires whether or not the loop actually parked on the pause."
  [!state !session agent-id]
  (when-let [note (runtime/take-resume-note! !state)]
    (when-let [st (get-in @!state [:behavior-tree :context :st-memory])]
      (swap! st (fn [s]
                  (-> s
                      (update :question
                              (fn [q]
                                (str (when-not (clojure.string/blank? (str q)) (str q "\n\n"))
                                     "[MID-RUN STEERING — you were paused and the user resumed the "
                                     "iteration loop with this added/updated instruction; treat it as "
                                     "authoritative and adjust your remaining work now] " note)))
                      (update :conversation (fnil conj [])
                              {:role "user" :content (str "[resumed from pause] " note)})))))
    (when @!session
      (swap! !session session/update-data
             {:trace {:agent-id agent-id
                      :content (str "iteration loop **resumed** with user request: " note)}}))
    (mulog/info ::resumed-with-user-note :agent-id agent-id)))

(defrecord Agent [agent-id !state !session]

  ;; ---- IAgent ----
  proto/IAgent
  (agent-id [_] agent-id)
  (agent-name [_] (get-in @!state [:meta :name] agent-id))
  (agent-description [_] (get-in @!state [:meta :description] ""))
  (user-id [_] (some-> !session deref :user-id))
  (session-id [_] (some-> !session deref :session-id))
  (defagent-type [_]
    (if-let [ns (and (keyword? agent-id) (namespace agent-id))]
      (keyword ns)
      agent-id))
  (process [this input ctx]
    (let [state @!state
          ;; Check for system commands
          sys-cmd (context/process-system-command input)]
      (if sys-cmd
        ;; Handle system command
        (let [{:keys [command args]} sys-cmd
              handler (get-in state [:config :system-commands command])]
          (if handler
            (handler args this)
            {:error (str "Unknown command: /" command)}))
        ;; Normal processing
        (let [bt (:behavior-tree state)]
          (if bt
            ;; BT-based processing
            (let [result (agent-bt/run-bt this input)
                  st-mem (get-in @!state [:behavior-tree :context :st-memory])]
              {:result result
               :answer (some-> st-mem deref :answer)})
            ;; Fallback: direct LLM processing via tool loop
            (let [tools (proto/get-tools this)]
              {:result :no-bt
               :tools (count tools)
               :input input}))))))
  (get-tools [_]
    (or (some-> @!state :st-memory-init deref :tools) []))
  (get-state [_] @!state)

  ;; ---- IAgentLifecycle ----
  proto/IAgentLifecycle
  (start-agent [this]
    (swap! !state assoc :status :idle)
    (register-agent this)
    (mulog/info ::agent-started :agent-id agent-id)
    this)
  (stop-agent [this]
    (runtime/cancel-run !state)
    (swap! !state assoc :status :stopped)
    (unregister-agent agent-id)
    (mulog/info ::agent-stopped :agent-id agent-id)
    this)
  (agent-running? [_]
    (boolean (#{:idle :running :paused :cancelled} (:status @!state))))
  (clone-agent [this] (proto/clone-agent this {}))
  (clone-agent [this opts]
    (let [{:keys [st-memory-init-overrides bt-config parent-agent]} opts

          ;; Generate new agent-id as keyword. The clone prefix flattens the
          ;; source id into a single namespace segment so nested clones stay clean:
          ;;   "react-agent"   -> "react-agent"
          ;;   :react-agent    -> "react-agent"
          ;;   :skill/planner  -> "skill.planner"
          clone-prefix (cond
                         (string? agent-id) agent-id
                         (namespace agent-id) (str (namespace agent-id) "." (name agent-id))
                         :else (name agent-id))
          clone-id (keyword clone-prefix (util/gen-random-words))

          ;; Snapshot current state
          state @!state
          src-config (:config state)
          src-bt (:behavior-tree state)

          ;; Snapshot st-memory (deref the atom inside BT context)
          st-memory-snapshot (when-let [st-atom (get-in src-bt [:context :st-memory])]
                               @st-atom)

          ;; Snapshot + override st-memory-init (mark as clone for lifecycle hooks)
          src-st-memory-init (when-let [a (:st-memory-init state)] @a)
          merged-st-memory-init (merge-with (fn [old new]
                                              (if (and (map? old) (map? new))
                                                (merge old new)
                                                new))
                                            (or src-st-memory-init {})
                                            (assoc (or st-memory-init-overrides {})
                                                   :cloned? true))

          ;; Build new agent state. :meta (identity: name/description/
          ;; agent-tools) is inherited from the source so the clone keeps the
          ;; same name and tool bag — agent-name/agent-description read it.
          initial-state {:meta (:meta state)
                         :config src-config
                         :memory-manager (:memory-manager state)
                         :session-store (:session-store state)
                         :runtime (runtime/create-runtime-state)
                         :st-memory-init (atom merged-st-memory-init)
                         :status :created}
          new-!state (atom initial-state)

          ;; Create clone (shared !session)
          clone (->Agent clone-id new-!state !session)]

      ;; Parent: explicit override > source's parent
      (runtime/set-parent-agent new-!state
                                (or parent-agent (runtime/get-parent-agent !state)))

      ;; BT: rebuild from bt-config, or reuse source's compiled tree
      (if bt-config
        ;; Build fresh BT from provided config
        (try
          (let [new-bt (agent-bt/build-bt bt-config clone
                                          :st-memory-init merged-st-memory-init)]
            (swap! new-!state assoc :behavior-tree new-bt))
          (catch Exception e
            (mulog/error ::clone-bt-build-failed :clone-id clone-id :error (ex-message e))
            (throw (ex-info "Clone BT build failed" {:clone-id clone-id} e))))
        ;; Reuse source's compiled tree with fresh context
        (when src-bt
          (let [new-bt {:tree (:tree src-bt)
                        :context {:st-memory (atom (or st-memory-snapshot {}))
                                  :agent clone}}]
            (swap! new-!state assoc :behavior-tree new-bt))))

      ;; Start and register
      (proto/start-agent clone)
      ;; Forward display events to shared !session for TUI rendering
      (attach-activity-forward-watch! clone)
      (mulog/info ::agent-cloned :source-agent-id agent-id :clone-agent-id clone-id)
      (hooks/fire! :agent.instance/created {:agent clone})
      clone))

  ;; ---- IAgentState ----
  proto/IAgentState
  (get-state-value [_ path]
    (get-in @!state path))
  (set-state-value! [_ path value]
    (swap! !state assoc-in path value))
  (get-bt [_]
    (:behavior-tree @!state))
  (get-bt-context [_]
    (get-in @!state [:behavior-tree :context]))
  (get-st-memory-init [_]
    (:st-memory-init @!state))

  ;; ---- IAgentBTIntegration ----
  ;; These methods are called by BT extended nodes in bt.clj via (.method agent ...)
  proto/IAgentBTIntegration
  (update-session-data [_ data]
    (when @!session
      (swap! !session session/update-data data)))

  (check-run-cancelled? [_]
    (runtime/cancelled? !state))

  (check-run-paused? [_]
    (runtime/paused? !state))

  (await-resume [_]
    (runtime/wait-if-paused !state))

  (apply-resume-note! [_]
    (inject-resume-note! !state !session agent-id))

  (create-action-promise [_ action-id]
    (runtime/create-action-promise !state action-id))

  (get-action-permission [_ action-id]
    (runtime/get-action-permission !state action-id))

  (set-action-permission [_ action-id value]
    (runtime/set-action-permission !state action-id value))

  (get-bt-st-memory [_]
    (get-in @!state [:behavior-tree :context :st-memory]))

  ;; ---- IAgentMemoryAccess ----
  proto/IAgentMemoryAccess
  (get-memory-manager [_]
    (:memory-manager @!state))

  ;; ---- java.io.Closeable ----
  java.io.Closeable
  (close [this]
    (detach-activity-forward-watch! this)
    (hooks/fire! :agent.instance/closed {:agent this})
    (let [mm (:memory-manager @!state)]
      (proto/stop-agent this)
      ;; Release persistent sandbox reference for GC
      (swap! !state dissoc :sandbox)
      ;; Stop the memory capture pipeline only when this was the last
      ;; agent referencing the manager. proto/stop-agent already
      ;; unregistered us, so list-agents reflects the post-close state.
      (when (and mm (mem/capture-running? mm))
        (let [siblings (filter #(identical? mm (proto/get-memory-manager %))
                               (vals @!agent-registry))]
          (when (empty? siblings)
            (try (mem/stop-capture! mm)
                 (catch Exception e
                   (mulog/warn ::capture-stop-failed
                               :agent-id agent-id
                               :error (ex-message e))))))))
    (mulog/info ::agent-closed :agent-id agent-id)))

;; ============================================================================
;; Agent Factory
;; ============================================================================

(defn- create-agent
  "Create a new Agent instance. Internal — call setup-agent instead.

   Parameters:
     user-id    - User identifier (stored on the agent-session, not the record)
     session-id - Agent-session identifier (stored on the agent-session)
     agent-id   - Globally-unique instance id, conventionally :<defagent-type>/<suffix>

   Options:
     :meta           - Agent identity map {:name :description :agent-tools} set
                       at creation; readers use `(get-in @!state [:meta :name])`
                       and `proto/agent-name` / `proto/agent-description`.
     :config         - Non-schema agent-meta-extras (e.g. :slack, :system-commands).
                       Schema-shape overrides live in `(:config @st-memory-init)`
                       and are read via `config/get-config`.
     :bt-config      - Behavior tree configuration vector
     :memory-manager - Pre-built memory manager (skips auto-creation)
     :memory-opts    - Options for memory manager creation {:in-memory :base-path :db-path}
                       Defaults to in-memory when not specified.
     :session-store  - ISessionStore instance for session persistence
     :parent-agent   - Parent agent for sub-agent hierarchy (inherits !session;
                       user-id/session-id args are ignored in that case)
     :st-memory-init - Initial short-term memory map (stored as atom in !state)

   Returns: Agent instance (not yet started)"
  [user-id session-id agent-id
   & {:keys [meta config bt-config memory-manager memory-opts
             session-store parent-agent st-memory-init]
      :or {meta {} config {} memory-opts {} st-memory-init {}}}]

  ;; Create or use provided memory manager (always created, defaults to in-memory)
  (let [mm (or memory-manager
               (agent-mem/create-memory-manager user-id
                                                :in-memory (:in-memory memory-opts)
                                                :base-path (:base-path memory-opts)
                                                :db-path (:db-path memory-opts)))

        ;; Session initialization priority:
        ;; 1. parent-agent's session (sub-agents always inherit)
        ;; 2. get-or-create from session store (shared with other agents/UI)
        ;; 3. standalone atom (no store)
        !session (if parent-agent
                   (:!session parent-agent)
                   (session/get-or-create-session
                    session-store session-id user-id
                    :config (:session-config config)))

        ;; Ensure session has a usage tracker before agent creation
        ;; (idempotent — skips if parent already created one)
        _ (when-not (session/get-session-config @!session :usage-tracker)
            (swap! !session session/set-session-config :usage-tracker (llm/create-usage-tracker)))

        ;; Build initial state — fully populated before ->Agent construction
        runtime-state (cond-> (runtime/create-runtime-state)
                        parent-agent (assoc :parent-agent parent-agent))

        ;; Lifecycle hooks are now global (see core.hooks); no parent->child
        ;; propagation needed because a single registered handler sees both
        ;; the parent and the sub-agent automatically. Use match predicates
        ;; (match-root-agent, match-defagent-type) when scoping is required.

        initial-state {:meta meta
                       :config config
                       :memory-manager mm
                       :session-store session-store
                       :runtime runtime-state
                       :st-memory-init (atom st-memory-init)
                       :status :created}

        !state (atom initial-state)

        ;; Create the agent record (user-id / session-id live on !session,
        ;; accessed via proto/user-id and proto/session-id).
        agent (->Agent agent-id !state !session)

        ;; Build BT if config provided (needs agent ref for context)
        _ (when bt-config
            (let [bt (agent-bt/build-bt bt-config agent
                                        :st-memory-init st-memory-init)]
              (swap! !state assoc :behavior-tree bt)))

        ;; Create Clojure agent for serialized async execution (needs agent ref)
        _ (swap! !state assoc :clj-agent (runtime/create-clj-agent agent))

        ;; Forward sub-agent display events to shared !session for TUI rendering
        _ (when parent-agent
            (attach-activity-forward-watch! agent))

        ;; Start the memory capture pipeline when enabled. The flag may
        ;; arrive on:
        ;;   - `:config` (low-level callers using @!state :config)
        ;;   - `(:config st-memory-init)` (unified per-agent override slot
        ;;     populated by setup-agent from defagent :config-extra schema
        ;;     keys + caller options).
        ;; start-capture! is idempotent per-manager, so calling it for
        ;; every agent that shares the same manager is safe.
        _ (when (and mm
                     (or (:enable-memory-capture config)
                         (:enable-memory-capture (:config st-memory-init))))
            (try (mem/start-capture! mm)
                 (catch Exception e
                   (mulog/warn ::capture-start-failed
                               :agent-id agent-id
                               :error (ex-message e)))))]

    (mulog/info ::agent-created :agent-id agent-id :user-id user-id :session-id session-id)
    (hooks/fire! :agent.instance/created {:agent agent})
    agent))

;; ============================================================================
;; Agent Execution Helpers
;; ============================================================================

(defn ask
  "Ask the agent a question. Main entry point for agent interaction.

   Handles:
   1. System commands (/cancel, /new, etc.)
   2. Memory recall
   3. BT execution
   4. Memory remember

   Parameters:
     agent - Agent instance
     input - User's input string

   Returns: response map with :answer/:error/:usage, or :error on invalid input

   `opts` (optional, default {}) carries ask metadata. `:source :wakeup` marks
   an auto-ask injected by task$wakeup — the input is recorded as a system
   message (not a user question) and :agent.ask/pre carries :source so the
   capture pipeline / prompt can distinguish a resumed turn from a fresh one."
  [agent input & [{:keys [source] :as _opts}]]
  ;; Validate agent
  (when-not (and agent (:!state agent) (:!session agent))
    (throw (ex-info "ask requires a valid agent with !state and !session" {:agent-id (:agent-id agent)})))
  ;; Validate input — accept :query fallback for LLMs that use wrong key
  (let [input (or input "")]
    (when (and (string? input) (clojure.string/blank? input))
      (throw (ex-info "ask requires a non-empty input" {:agent-id (:agent-id agent) :input input}))))
  (let [!state (:!state agent)
        !session (:!session agent)]
    ;; Reset runtime for new run
    (runtime/reset-runtime !state)
    (swap! !state assoc :status :running)

    ;; Bump two counters per ask:
    ;;   - per-agent :turn-id (this agent's monotonic ask count — used for
    ;;     display, previous-turns, and per-agent observability)
    ;;   - session :total-turns (cumulative count across root + sub-agents
    ;;     in the session — used as the audit row index combined with
    ;;     :session-id and :agent-id)
    ;; Both are mirrored into st-memory-init so BT actions (coact-init,
    ;; recall, dspy-action) can read them.
    (let [total-turns (session/inc-total-turns! !session)]
      (when-let [st-init (:st-memory-init @!state)]
        (let [{:keys [turn-id]} (swap! st-init update :turn-id (fnil inc 0))]
          (swap! st-init assoc :total-turns total-turns)
          ;; Reference turn-id so the binding isn't dropped (some BT actions
          ;; read it from the post-swap value via st-init).
          turn-id)))

    ;; Clear progress data (root agent only — sub-agents share parent's !session)
    (let [parent (runtime/get-parent-agent !state)]
      (when-not parent
        (swap! !session session/clear-data))

      ;; Root agent: user message; sub-agent: assistant message tagged with
      ;; parent's id; wakeup auto-ask: system message (not a user question).
      (swap! !session session/add-message
             (cond
               parent             (session/assistant-message input (:agent-id parent))
               (= source :wakeup) (session/system-message input)
               :else              (session/user-message input))))

    ;; Pre-ask hook: after status :running, before process
    (hooks/fire! :agent.ask/pre {:agent agent :input input :source source})

    (llm/with-active-stream-register
      (fn [stream]
        (if stream
          (runtime/set-active-http! !state stream)
          (runtime/clear-active-http! !state)))
      (try
        (let [result (proto/process agent input nil)
            ;; Include usage summary if tracker exists
              usage-summary (when-let [tracker (session/get-session-config @!session :usage-tracker)]
                              (llm/get-usage-summary tracker))
              result (cond-> result
                       usage-summary (assoc :usage usage-summary))
            ;; Finalize hook (gated): a handler may :replace the result —
            ;; e.g. inject an absent `Saved <kind>: <path>` handoff line for an
            ;; auto-persisted artifact. Runs BEFORE the session message + the
            ;; observe-only :agent.ask/post so both see the finalized answer.
              result (let [d (hooks/fire-decision! :agent.ask/finalize
                                                   {:agent agent :input input :result result})]
                       (if (= :replace (:result d)) (:replacement d) result))]
        ;; Add assistant response to session
          (when-let [answer (:answer result)]
            (swap! !session session/add-message
                   (session/assistant-message answer (:agent-id agent))))

        ;; Post-ask hook: after process, before status :idle
          (hooks/fire! :agent.ask/post {:agent agent :input input :result result})

          (swap! !state assoc :status :idle)
          result)

        (catch Exception e
          (swap! !state assoc :status :idle)
          (mulog/error ::agent-execution-failed :agent-id (:agent-id agent) :exception e)
        ;; Surface to the memory capture pipeline (when enabled) so
        ;; failures join the L2 timeline alongside the user/assistant
        ;; messages that bracketed them.
          (try (hooks/fire! :agent/exception
                            {:agent agent :phase :ask :exception e})
               (catch Exception _ nil))
        ;; Also fire `:agent.ask/post` so listeners that close out the
        ;; ask cycle (daemon status snapshot, TUI iteration block
        ;; freeze, activity-pane footer) flip back to idle even on
        ;; failure.  Without this a user-initiated cancel mid-LLM-call
        ;; leaves the status bar stuck at "running" forever — the BT
        ;; threw `Cancelled`, the success-path hooks/fire! at line 563
        ;; never ran, so the daemon never saw an :ask/post and the
        ;; pane chrome stayed in :running mode.
          (let [iters (try
                        (some-> ^ai.brainyard.agent.core.protocol.IAgentBTIntegration agent
                                .get-bt-st-memory deref
                                ((some-fn :iteration :iteration-count)))
                        (catch Throwable _ nil))
                result (cond-> {:error (ex-message e)}
                         iters (assoc :iteration-count iters))]
            (try (hooks/fire! :agent.ask/post
                              {:agent agent :input input :result result})
                 (catch Exception _ nil))
            result))

        (finally
        ;; Notify parent's TUI that this sub-agent is done
          (when (runtime/get-parent-agent !state)
            (fire-agent-done-activity! agent)))))))

(defn ask-async
  "Ask the agent a question asynchronously using a Clojure agent.
   Dispatches (ask agent input) via send-off. Back-to-back calls are
   automatically queued and executed sequentially.
   Returns the Clojure agent ref. Use (await clj-ag) then (:output @clj-ag)
   to get the result, or add-watch for reactive notification.

   `opts` (default {}) is forwarded to `ask` — e.g. `{:source :wakeup}` for
   task$wakeup auto-asks. Back-to-back sends (user turn + wakeup) are queued
   and run sequentially by the Clojure agent, so a wakeup can never race a
   live turn."
  ([agent input] (ask-async agent input {}))
  ([agent input opts]
   (let [clj-ag (:clj-agent @(:!state agent))]
     (runtime/send-ask clj-ag ask agent input opts))))

(defonce ^{:doc "Host-registered turn submitter — see register-turn-submitter!."}
  !turn-submitter (atom nil))

(defn register-turn-submitter!
  "Register a host fn `(fn [agent input opts])` that submits a turn through the
   host's OWN single executor (e.g. the TUI input queue). Auto-asks injected by
   task$wakeup go through `submit-turn`, which uses this when set — so a wakeup
   serializes with user turns on the same queue instead of racing them on a
   separate executor. Unset (headless / single-executor host) → submit-turn
   falls back to ask-async."
  [f]
  (reset! !turn-submitter f))

(defn submit-turn
  "Submit `input` as a turn for `agent`, forwarding `opts` (e.g.
   {:source :wakeup}) to `ask`. Routes through the host turn-submitter when one
   is registered (serializes with user turns), else via ask-async."
  [agent input opts]
  (if-let [f @!turn-submitter]
    (f agent input opts)
    (ask-async agent input opts)))

(defn deliver-action
  "Deliver a user response to a pending action promise."
  [agent action-id value]
  (runtime/deliver-action-response (:!state agent) action-id value))

;; ============================================================================
;; Get or Create Agent (cloudcast-compatible)
;; ============================================================================

(defn- get-or-create-agent
  "Get an existing agent instance (by globally-unique agent-id) or create a new one.
   Uses double-check locking to prevent duplicate creation under concurrency.
   Internal — call setup-agent instead.

   Parameters:
     user-id    - User identifier (used to init the agent-session if new)
     session-id - Agent-session identifier (used to init the agent-session if new)
     agent-id   - Globally-unique instance id (:<defagent-type>/<suffix>)
     options    - Map of create-agent options (same keys: :config :bt-config
                  :st-memory-init :memory-opts :parent-agent etc.)

   Returns: Agent instance (started)"
  [user-id session-id agent-id options]
  (or (get-agent agent-id)
      (let [lock (get-or-create-lock agent-id)]
        (locking lock
          ;; Double-check after acquiring lock
          (or (get-agent agent-id)
              (let [agent (apply create-agent user-id session-id agent-id
                                 (mapcat identity options))]
                (proto/start-agent agent)
                agent))))))

;; ============================================================================
;; Generic Agent Setup & Runner
;; ============================================================================

(defn setup-agent
  "Create/retrieve an agent from options. Returns the started Agent record.
   Does NOT call ask/ask-async — caller controls dispatch.

   Reads all configuration from the options map. When called via deftool wrapper,
   defagent metadata is automatically merged into options.

   Key options (typically from defagent metadata):
     :id             - agent id keyword. Must be globally unique; should follow
                       the :<defagent-type>/<suffix> convention. If omitted,
                       one is auto-generated via `generate-instance-id`.
     :bt-factory     - (fn [options] bt-config)
     :agent-tools    - tool map to bind, or nil
     :instruction    - system prompt
     :tool-context   - tool usage context
     :agent-context  - additional context
     :max-iterations - max BT loop iterations

   Runtime options:
     :agent-session   - {:user-id :session-id} (required) — the agent-session
                        scope; sub-agents inherit this from :parent-agent's session.
     :parent-agent    - parent agent (if sub-agent call)
     :memory-opts     - memory manager options
     :config-extra    - map of agent-level defaults. Keys are split at
                        setup: schema-shape keys (in config-schema) flow
                        into st-memory-init :config (the per-agent
                        override layer read by config/get-config);
                        non-schema keys (e.g. :permissions) flow into
                        the agent's @!state :config metadata slot.
     :st-memory-extra - map merged into :st-memory-init
     :session-store   - custom session store

   Schema-key options at the top level of `options` (e.g. :eval-lm,
   :max-refinements) are extracted into st-memory-init :config and win
   over defagent author defaults supplied via :config-extra. Read them
   back via (config/get-config agent :key)."
  [& {:keys [id bt-factory agent-tools instruction tool-context
             agent-context max-iterations parent-agent
             config-extra st-memory-extra session-store
             _deftool$id _deftool$description]
      {:keys [user-id session-id]} :agent-session
      :as options}]
  (let [;; Resolve instance-id: explicit :id wins; otherwise derive from the
        ;; defagent's registered id (carried by the deftool wrapper as
        ;; :_deftool$id). Without this fallback, callers reaching setup-agent
        ;; via invoke-tool would land here with no id and produce an Agent
        ;; record with :agent-id nil, which crashes downstream hooks that
        ;; call (namespace agent-id).
        instance-id (or id
                        (when _deftool$id (generate-instance-id _deftool$id)))
        _ (when-not (keyword? instance-id)
            (mulog/error ::setup-agent-invalid-instance-id
                         :id id
                         :_deftool$id _deftool$id
                         :user-id user-id
                         :session-id session-id)
            (throw (ex-info
                    (str "setup-agent could not resolve a valid instance-id. "
                         "Pass :id (keyword) or invoke via a registered defagent "
                         "so :_deftool$id is supplied.")
                    {:id id
                     :_deftool$id _deftool$id
                     :user-id user-id
                     :session-id session-id})))
        ;; Ensure global config is loaded once (lazy + idempotent). Reads
        ;; .brainyard/config.edn :auto and merges over default-config.
        _ (config/load-global-config!)
        ;; Resolve max-iterations: explicit arg > defagent meta > schema default
        max-iterations (or max-iterations
                           (get config/default-config :max-iterations 100))
        options (assoc options :max-iterations max-iterations)
        ;; Bind tools if agent-tools present. Pass :agent-id so bind-tools can
        ;; drop tools hidden by :tool-use-control (visibility :hidden / allow /
        ;; deny patterns) — keeps the LLM JSON tool-calls roster in sync with
        ;; what's actually callable.
        [tools tools-fn-map] (when agent-tools
                               (tool/bind-tools (assoc agent-tools :agent-id instance-id)))
        ;; Build BT from factory
        bt-config (when bt-factory (bt-factory options))
        ;; Split :config-extra into schema-shape overrides (→ st-mem-init :config)
        ;; vs. non-schema agent metadata (→ @!state :config). Caller options that
        ;; collide with config-schema keys win over defagent author defaults.
        schema-overrides  (merge (select-keys config-extra config/config-keys)
                                 (select-keys options config/config-keys))
        agent-meta-extras (apply dissoc config-extra config/config-keys)
        ;; Build st-memory-init. `:config` is the canonical per-agent
        ;; override slot — readers use `config/get-config` to resolve.
        st-init (cond-> {:tool-context   tool-context
                         :instruction    instruction
                         :agent-context  agent-context
                         :config         schema-overrides}
                  tools        (assoc :tools tools)
                  tools-fn-map (assoc :tools-fn-map tools-fn-map))
        st-init (if st-memory-extra (merge st-init st-memory-extra) st-init)
        ;; @!state :meta — immutable agent identity set at creation.
        agent-meta {:name        (subs (str instance-id) 1)
                    :description _deftool$description
                    :agent-tools agent-tools}
        ;; @!state :config — non-schema agent-meta extras only
        ;; (e.g. :slack, :system-commands). Schema overrides live in
        ;; (:config @st-memory-init) and are read via config/get-config.
        agent-config agent-meta-extras
        ;; Create/retrieve agent
        create-opts (cond-> {:meta           agent-meta
                             :config         agent-config
                             :bt-config      bt-config
                             :st-memory-init st-init
                             :memory-opts    (:memory-opts options)
                             :parent-agent   parent-agent}
                      session-store (assoc :session-store session-store))]
    (get-or-create-agent user-id session-id instance-id create-opts)))

(defn setup-agent-by-id
  "Look up a registered defagent by its defagent-type, resolve its metadata, and
   create/start an instance. Returns the started Agent record.
   Does NOT call ask/ask-async.

   Resolves the defagent metadata from the tool registry, merges with caller
   options, and delegates to setup-agent. Use this from TUI/web entry points
   that need to customize the agent after creation.

   The instance-id defaults to (generate-instance-id agent-id), i.e.
   :<defagent-type>/<suffix>. Callers may override by passing an explicit :id
   (should also be a namespaced keyword, e.g. :coact-agent/my-run).

   Options (merged with defagent metadata):
     :id               - override instance-id (must be unique)
     :agent-session    - {:user-id :session-id} (required) — the agent-session
     :max-iterations   - override default
     :config-extra     - map merged into :config
     :st-memory-extra  - map merged into :st-memory-init
     :session-store    - custom session store"
  [agent-id & {:keys [id] :as options}]
  (let [def-entry (tool/get-tool-defs :id agent-id)
        _ (when-not def-entry
            (throw (ex-info (str "Agent not found in registry: " agent-id)
                            {:agent-id agent-id})))
        instance-id (or id (generate-instance-id agent-id))
        merged (merge (:meta def-entry) options {:id instance-id})]
    (apply setup-agent (mapcat identity merged))))

(defn- close-agent-quietly!
  "Close an agent without letting exceptions escape."
  [^java.io.Closeable ag]
  (try (.close ag) (catch Exception _)))

(defn- attach-auto-close-watch!
  "Attach a one-shot watch to a Clojure agent ref that closes the brainyard
   agent when the async ask completes (state transitions to a non-nil :output)."
  [clj-ref ag]
  (add-watch clj-ref ::auto-close
             (fn [k _ref old new]
               (when (and (nil? (:output old)) (some? (:output new)))
                 (close-agent-quietly! ag)
                 (remove-watch clj-ref k)))))

(defn run-agent
  "Generic agent runner — setup + ask. Used as the function in defagent registrations.
   For cases where you need the Agent record (to add watches, permissions, etc.),
   use setup-agent or setup-agent-by-id instead.

   By default, uses ask-async (returns clojure agent ref) when no parent-agent,
   and synchronous ask when parent-agent is set. Override with :ask-async? true
   to force async even with a parent-agent.

   Options:
     :setup-only? - Return the Agent record without calling ask. Useful for entry
                    points (TUI, web) that need to configure the agent (permissions,
                    watches) before the first ask. :auto-close? is ignored in this mode.
     :auto-close? - Close the agent after ask completes. For sync ask, closes in a
                    finally block. For async ask, attaches a one-shot watch that
                    closes when the clj-agent's :output transitions to non-nil.
                    Defaults to true for sub-agent calls (see do-call-tool--agent)."
  [& {:keys [question query parent-agent ask-async? setup-only? auto-close?] :as options}]
  (let [question (or question query "")]
    (when (and (not setup-only?)
               (or (nil? question) (and (string? question) (clojure.string/blank? question))))
      (throw (ex-info "run-agent requires a non-empty :question" {:question question})))
    (let [ag (apply setup-agent (mapcat identity (assoc options :question question)))]
      (cond
        setup-only?
        ag

        (or ask-async? (not parent-agent))
        (let [clj-ref (ask-async ag question)]
          (when auto-close? (attach-auto-close-watch! clj-ref ag))
          clj-ref)

        :else
        (try
          (ask ag question)
          (finally
            (when auto-close? (close-agent-quietly! ag))))))))
